### ISSUE TITLE
Document your research about GitHub under GitHub Research wiki page

### ISSUE THREAD

**Issue by simitii** [bounswe/bounswe2019group3#3]
- [x]  Samet Demir  
- [ ]  Egemen Kaplan  
- [x]  Cihat Kapusuz
- [x]  Burak İlkay Akgün
- [ ]  Bartu Ören
- [ ]  Orkan Akısü
- [x]  Ahmet Mert Tahran
- [x]  Yağmur Kahyaoğlu
- [ ]   Muhammet Ekrem Gezgen
- [x] Hilal Demir

assignment 1 - clause 8

Document the following research you will perform:
• Explore GitHub repositories to discover repos that you like. Document them by
giving their references and describing what you liked.
• Study git as a version management system. There are many guides and videos you can watch. I recommend Git For Ages 4 And Up (https://youtu.be/1ffBJ4sVUb4). It is long, but very good. However, you can choose a different resource if you prefer.

**Comment by simitii** [comment]
@EgemenKaplan @orenbartu @orkana @ekremgezgen 
let's complete and close this issue

**Comment by uskudarli** [comment]
Since this has been here very long, it seems a good idea to close it and open issues specific to those who have not completed their part. 

As such @simitii has requested to complete and close... In order to acknowledge part that is done, you can close this and reopen for @EgemenKaplan @orenbartu @orkana @ekremgezgen (if still relevant)
