### ISSUE TITLE
Editing Project Plan

### ISSUE THREAD

**Issue by buzem** [bounswe/bounswe2019group3#91]
According to review , in project plan, there should be the things what we will do rather than what we have done,so it needs to be edited

**Comment by simitii** [comment]
@burakilkayakgun You are familiar with the program that we use for the project plans. So, would you please handle this one?

**Comment by burakilkayakgun** [comment]
Yeah, I'll take care of the project plan.

**Comment by simitii** [comment]
@burakilkayakgun 

Since the Milestone 1, the backend team completed followings:
(descriptions in issues)
#87 
#88 
#89 
#86 

Here are the remaining tasks (abstract descriptions):
- Design and Implementation of User Progress API
    - Get progress for an exercise
    - Get overall progress in a given language
- Design and Implementation of Writing API
    - Save writing
    - List the saved writings of a user
    - Send saved writing to other users for evaluation 
    - Recommendation: Get recommended users for a (writing, user) pair
- Design and Implementation of Annotations API
    - List the annotators for an entity given entity type, entity id
    - Get annotations created by the annotator related to the entity given entity type, entity id, annotator username
    - Create and/or Update annotations related to the entity given entity type, entity id, and annotation body
